### ISSUE TITLE
Partition scheme file format inconsistent with the manual

### ISSUE THREAD

**Issue by BenoitMorel** [ddarriba/modeltest#12]
Modeltest manual says in 5.4:
> • DATA TYPE can be DNA or PROTEIN
Modeltest code says in https://github.com/ddarriba/modeltest/blob/master/src/utils.cpp#L591:
`else if (!strcasecmp(tmpchar,"PROT") || !strcasecmp(tmpchar,"AA")) `

Also, it would be nice to have an example of the partition scheme file format in the wiki or in the examples.

**Comment by ddarriba** [comment]
Thanks a lot Benoit! I fixed the manual, and also added the partitioning schemes format in the wiki: https://github.com/ddarriba/modeltest/wiki/Input-Data
