### ISSUE TITLE
   ...building pll ...pll FAIL!

### ISSUE THREAD

**Issue by almamelisa** [ddarriba/modeltest#18]
Hi!

I'm trying to install jmodeltest-ng and I obtained this error:
Using Qt version 5.6.2 in /Users/BEHB/anaconda/bin/lib
...configuration:
   prefix:       /modeltest/modeltest-0.1.3/build
   build:        /modeltest/modeltest-0.1.3/build
   pll:          [yes] /modeltest/modeltest-0.1.3/libs/pll-modules/libs/libpll
   modules:      [yes] /modeltest/modeltest-0.1.3/libs/pll-modules
      include:   /modeltest/modeltest-0.1.3/build/include
      lib:       /modeltest/modeltest-0.1.3/build/lib

...writing log to /modeltest/modeltest-0.1.3/build.log
...build pll
   ...building pll
...pll FAIL!

 when I do ./build.sh

**Comment by ddarriba** [comment]
Could you please post your build.log file? You can also try using cmake:

$ mkdir build && cd build
$ cmake ..
$ make

**Comment by almamelisa** [comment]
Yes, 
configure arguments: CPPFLAGS=-I/analisis/modeltest-ng-0.1.3/build/include LDFLAGS=-L/analisis/modeltest-ng-0.1.3/build/lib --prefix /analisis/modeltest-ng-0.1.3/build 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/analisis/modeltest-ng-0.1.3/libs/pll-modules/libs/libpll':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

**Comment by ddarriba** [comment]
It seems you don't have a C compiler. You should install gcc first.

**Comment by filipevictoria** [comment]
Dear darriba

I have an other issue to install the Modeltest-NG in Mac OS Catalina.

In my build log only report as:

./build.sh: line 130: autoreconf: command not found

**Comment by ktmeaton** [comment]
Here was my solution to the following issue:
```
...build pll
   ...building pll
...pll FAIL!
```

Inspecting build.log revealed that I did not have the FLEX or BISON pre-requisites. Here are my steps, from the beginning.

Install flex and bison:
```
conda install flex bison
```
(Note: I also have the following conda packages installed: cmake, autoconf, and automake.

Clone the modeltest-ng repo, version control to the v0.1.6 release:
```
git clone --recursive https://github.com/ddarriba/modeltest.git
git checkout v0.1.6
```

Edit build.sh to disable building gui:
```
build_gui=no             # build modeltest-gui
```

Run the build script:
```
./build.sh
```

My build output now says (this is Windows Subsystem for Linux):
```
Running install script for Linux
...configuration:
   prefix:       /mnt/c/Users/ktmeaton/Programs/modeltest/build
   build:        /mnt/c/Users/ktmeaton/Programs/modeltest/build
   pll:          [yes] /mnt/c/Users/ktmeaton/Programs/modeltest/libs/pll-modules/libs/libpll
   modules:      [yes] /mnt/c/Users/ktmeaton/Programs/modeltest/libs/pll-modules
      include:   /mnt/c/Users/ktmeaton/Programs/modeltest/build/include
      lib:       /mnt/c/Users/ktmeaton/Programs/modeltest/build/lib

...writing log to /mnt/c/Users/ktmeaton/Programs/modeltest/build.log
...build pll
   ...building pll
...pll OK!
/mnt/c/Users/ktmeaton/Programs/modeltest
...build modules
   ...building modules
...modules OK!
/mnt/c/Users/ktmeaton/Programs/modeltest
...build modeltest
...modeltest OK!
...skip modeltest GUI
```
