### ISSUE TITLE
Tree distances

### ISSUE THREAD

**Issue by ddarriba** [ddarriba/modeltest#2]
Implement tree distances.

For example, DT criterion is based on topological distances. Hence it makes no sense to compute it with fixed topologies.

**Comment by lixingguang** [comment]
Could not find mode test for binary data?

**Comment by lixingguang** [comment]
@ddarriba can this be used for binary data?

**Comment by ddarriba** [comment]
Sorry, I am not aware of substitution models for binary data apart from a 2-state GTR. This model is supported by (e.g.,) RAxML-NG.
