### ISSUE TITLE
Support phylip interleaved format

### ISSUE THREAD

**Issue by BenoitMorel** [ddarriba/modeltest#28]
Hi Diego,

Modeltest-ng does not support some phylip files that raxml-ng supports (see original issue and example alignment here: https://groups.google.com/forum/#!topic/raxml/n7-NiVepOgw).

This is because libpll offers two functions (`pll_phylip_parse_sequential`and `pll_phylip_parse_interleaved`) that parse two different kind of phylip files, but you only try the first one: https://github.com/ddarriba/modeltest/blob/master/src/msapll.cpp#L420

If you don't have the time to fix it, I can also submit a pull request next week.

Greetings from Heidelberg ;-)
Benoit

**Comment by ddarriba** [comment]
Hi Benoit,

Thank you for the advice! I added support for it and committed the changes into the dev branch.

Cheers!
Diego.
