### ISSUE TITLE
Can not build on Ubuntu Xenial

### ISSUE THREAD

**Issue by hinz1** [ddarriba/modeltest#34]
I tried several of the ways to compile described in the Wiki (cmake, autotools, script...) each failing for one reason or another, finally trying "Compiling manually (Linux and OS X)" from here: https://github.com/ddarriba/modeltest/wiki/Download-and-Install 

I succeeded with 1) libp11
When trying to build the p11-modules starting with autoreconf -i and ./configure I get

...
checking pll.h usability... no
checking pll.h presence... no
checking for pll.h... no
configure: error: pll.h not found

The packages libp11-dev and p11-kit-dev are installed, in case that makes a difference.

**Comment by ddarriba** [comment]
Please try the build script. Just run ./build.sh on the ModelTest directory. The missing dependency is not P11 but PLL, but you do not have to worry about that. The build script should work.

**Comment by hinz1** [comment]
Sigh. Thank you for your reply. **It did perfectly**. 
No idea what went wrong the first time I tried. 
Anyway, concerning P11/PLL: Some of these days I'll say terribly rude things to a random font designer. ;)
