### ISSUE TITLE
Problem in creating manual.pdf: couldn't open style file natbib.bst

### ISSUE THREAD

**Issue by AlessandroGorohovski** [ddarriba/modeltest#39]
Dear Modeltest tead,

Thanks a lot for your Modeltest program!
Sorry, I am trying to create manual.pdf using make (in 'manual/' subdir).
When executed I get the an error.
This is what I am doing: 
$ make

OUTPUT
<...truncated...>

Output written on manual.pdf (16 pages, 388829 bytes).
Transcript written on manual.log.
bibtex manual
This is BibTeX, Version 0.99d (TeX Live 2013/Debian)
The top-level auxiliary file: manual.aux
A level-1 auxiliary file: sec-quickstart.aux
A level-1 auxiliary file: sec-arguments.aux
I couldn't open style file natbib.bst
---line 32 of file manual.aux
 : \bibstyle{natbib
 :                 }
I'm skipping whatever remains of this command
I found no style file---while reading file manual.aux
(There were 2 error messages)

I think the problem is that I have sty file, but no bst file.
$ kpsewhich natbib.sty
/home/alessandro/texmf/tex/latex/natbib/natbib.sty

$ kpsewhich natbib.bst
<empty>

Can any one help on this?
Thank you very much in advance,
Alessandro

**Comment by ddarriba** [comment]
I added the missing file to the repository.

**Comment by AlessandroGorohovski** [comment]
I cannot but admire your work.
Many Thanks!
