### ISSUE TITLE
Support PHYLIP iterleaved formated MSA

### ISSUE THREAD

**Issue by vincent-lefort** [ddarriba/modeltest#45]
I tried to run Modeltest-ng on a PHYLIP interleaved formated file. I got the error message:
modeltest-ng: Cannot parse the msa: in.phy
              [910]: Sequence 1 (T1) longer than expected

I converted the input MSA into a PHYLIP sequential formated file and Modeltest-ng ran succesfully.

Is there a chance for the next Modelttest-ng release to support PHYLIP interleaved formated MSA?

**Comment by ddarriba** [comment]
Hi Vincent,

PHYLIP interleaved was already supported in v0.1.7 in the development branch. I updated the master branch to the most recent version, so it should work now.
