### ISSUE TITLE
Segfault running on aa MSA

### ISSUE THREAD

**Issue by rcedgar** [ddarriba/modeltest#46]
Command line:

`modeltest-ng-static -i nido_wolftrim.afa -d aa -p 10`

Downloaded today, release `v0.1.6`, version `modeltest x.y.z`  according to `--version`

Alignment and log posted here:

[https://drive5.com/tmp/nido_wolftrim.tar.gz](https://drive5.com/tmp/nido_wolftrim.tar.gz)

**Comment by ddarriba** [comment]
This is a known bug with the static binary and pthreads. You can either run the static version with a single thread or compile the source code. I will upload the 0.1.7 release package (hopefully) tomorrow.

**Comment by ddarriba** [comment]
Fixed! Also the [static binary](https://github.com/ddarriba/modeltest/files/6192913/modeltest-ng-0.1.7-static.tar.gz) is available.
