### ISSUE TITLE
Version information printed twice

### ISSUE THREAD

**Issue by jtklein** [ddarriba/modeltest#47]
When I run "modeltest-ng.exe --version" (compiled on Windows) some information about the version is printed twice to the console:
                             _      _ _            _      _   _  _____ 
                            | |    | | |          | |    | \ | |/ ____|
         _ __ ___   ___   __| | ___| | |_ ___  ___| |_   |  \| | |  __
        | '_ ` _ \ / _ \ / _` |/ _ \ | __/ _ \/ __| __|  | . ` | | |_ |
        | | | | | | (_) | (_| |  __/ | ||  __/\__ \ |_   | |\  | |__| |
        |_| |_| |_|\___/ \__,_|\___|_|\__\___||___/\__|  |_| \_|\_____|
--------------------------------------------------------------------------------
ModelTest-NG v0.1.7 released on 17.03.2021 by The Exelixis Lab.
Written by Diego Darriba.
Contributors: Tomas Flouri, Alexey Kozlov, Benoit Morel, David Posada,
              Alexandros Stamatakis.
Latest version: https://github.com/ddarriba/modeltest
--------------------------------------------------------------------------------

ModelTest-NG v0.1.7 released on 17.03.2021 by The Exelixis Lab.
Written by Diego Darriba.
Contributors: Tomas Flouri, Alexey Kozlov, Benoit Morel, David Posada,
              Alexandros Stamatakis.
Latest version: https://github.com/ddarriba/modeltest

**Comment by ddarriba** [comment]
I could not reproduce this error (I have Windows 10 on a virtual machine). Could you please explain the compilation and execution process you followed?
