### ISSUE TITLE
Error trying to run modeltest-ng, exited with code 'SIGILL'.

### ISSUE THREAD

**Issue by jtklein** [ddarriba/modeltest#49]
Hello,
a client of ours could not run the ModelTest binary on his new MacBook with the new M1 chip architecture.
The error thrown was "Error trying to run modeltest-ng, exited with code 'SIGILL'."
I do not have access to the hardware to examine more, but maybe the code is not compiled correctly for the new chips.

**Comment by ddarriba** [comment]
I finally could compile the ARM binary. Could you please try it? 

[modeltest-ng OSX ARM](https://github.com/ddarriba/modeltest/files/6580170/modeltest-ng-osx.tar.gz)

**Comment by jtklein** [comment]
Thank you so much for this binary. The user reported that it works now on his machine.
